### ISSUE TITLE
requirements file versions

### ISSUE THREAD

**Issue by dominikacecylia** [ijauregiCMCRC/Shared_Attention_for_APE#2]
Hi,

I am trying to run the scripts in Google Colab but I struggle with identifying version of torch, six, tqdm, torchtext, future.
Could you please specify on which versions did you run your project?

Best,
Dominika

**Comment by inigo-jauregi** [comment]
Hi Dominika,

Sorry for that. I didn't document very well the project at the time.

`torch==0.4.0`
`torchtext==0.2.1`

and that should install the approiate `six`, `tqdm` and `future`.

**Comment by dominikacecylia** [comment]
Thank you for the answer, I was able to run the whole script.
